name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-b59251f52d487be26e75eaeed-nonprodbucket-1e3l99mt1wetq
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build site
        run: |
          npm ci
          npm run build
      - name: deploy files to bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }} --recursive --acl public-read
